grafana:
  enabled: true

  adminUser: admin

  adminPassword: admin123

  service:
    type: NodePort

prometheus:

  prometheusSpec:

    retention: 2d

    storageSpec: {}

alertmanager:
  enabled: false